name: Deploy ke Web

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Simulasi Deploy (echo saja)
      run: echo "Deploy sukses - commit terbaru sudah diupload!"
